[package]
name = "sui"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.88"
serde_yaml = "0.8.26"
signature = "1.6.0"
camino = "1.1.1"
tokio = { workspace = true, features = ["full"] }
async-trait = "0.1.57"
serde_with = { version = "2.1.0", features = ["hex"] }
tracing = "0.1.36"
bcs = "0.1.4"
clap = { version = "3.2.17", features = ["derive"] }
bip32 = "0.4.0"

sui-adapter = { path = "../sui-adapter" }
sui-core = { path = "../sui-core" }
sui-framework = { path = "../sui-framework" }
sui-framework-build = { path = "../sui-framework-build" }
sui-config = { path = "../sui-config" }
sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
sui-swarm = { path = "../sui-swarm" }
sui-json-rpc-types = { path = "../sui-json-rpc-types" }
sui-sdk = { path = "../sui-sdk" }
sui-keys = { path = "../sui-keys" }
sui-source-validation = { path = "../sui-source-validation" }

fastcrypto.workspace = true

rustyline = "9.1.2"
rustyline-derive = "0.7.0"
colored = "2.0.0"
unescape = "0.1.0"
shell-words = "1.1.0"
rocksdb = "0.19.0"

tempfile = "3.3.0"
narwhal-executor = { path = "../../narwhal/executor" }
telemetry-subscribers.workspace = true
typed-store.workspace = true
typed-store-derive.workspace = true
mysten-network.workspace = true

move-core-types.workspace = true
move-prover.workspace = true
move-prover-boogie-backend.workspace = true
move-stackless-bytecode.workspace = true
move-unit-test.workspace = true
move-cli.workspace = true
move-package.workspace = true

workspace-hack.workspace = true
multiaddr = "0.17.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemalloc-ctl = "^0.5"

[dev-dependencies]
tempfile = "3.3.0"
futures = "0.3.23"
prometheus = "0.13.3"

jsonrpsee = { git="https://github.com/patrickkuo/jsonrpsee.git", rev= "adc19a124ed7045744442ca67f084ddfba4ba177", features = ["full"] }

test-utils = { path = "../test-utils" }
rand = "0.8.5"
move-package.workspace = true
sui-core = { path = "../sui-core" }
sui-node = { path = "../sui-node" }
sui-macros = { path = "../sui-macros" }
sui-simulator = { path = "../sui-simulator" }
mysten-metrics = { path = "../mysten-metrics" }

assert_cmd = "2.0.6"

[package.metadata.cargo-udeps.ignore]
normal = ["jemalloc-ctl"]
