[package]
name = "sui-json-rpc"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
fastcrypto.workspace = true
fastcrypto-tbls.workspace = true
jsonrpsee = { git="https://github.com/patrickkuo/jsonrpsee.git", rev= "adc19a124ed7045744442ca67f084ddfba4ba177", features = ["full"] }
jsonrpsee-proc-macros = {git="https://github.com/patrickkuo/jsonrpsee.git", rev= "adc19a124ed7045744442ca67f084ddfba4ba177"}
hyper = "0.14"
tower = "0.4.12"
tower-http = { version = "0.3.4", features = ["full"] }
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
prometheus = "0.13.3"
anyhow = "1.0.64"
tracing = "0.1.36"
async-trait = "0.1.57"
serde = { version = "1.0.144", features = ["derive"] }
futures = "0.3.23"
tokio = { workspace = true, features = ["full"] }
signature = "1.6.0"
thiserror = "1.0.37"
bcs = "0.1.4"

tap = "1.0"

sui-adapter = { path = "../sui-adapter" }
sui-core = { path = "../sui-core" }
sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
sui-open-rpc = { path = "../sui-open-rpc" }
sui-open-rpc-macros = { path = "../sui-open-rpc-macros" }
sui-json-rpc-types = { path = "../sui-json-rpc-types" }
sui-cost = { path = "../sui-cost" }
sui-transaction-builder = { path = "../sui-transaction-builder" }
mysten-metrics = { path = "../mysten-metrics" }
workspace-hack.workspace = true

[dev-dependencies]
sui-config = { path = "../sui-config" }
sui-framework-build = { path = "../sui-framework-build" }
sui-keys = { path = "../sui-keys" }
test-utils = { path = "../test-utils" }
sui-sdk = { path = "../sui-sdk" }
rand = "0.8.5"
sui-macros = { path = "../sui-macros" }
sui-simulator = { path = "../sui-simulator" }
