(function() {var implementors = {
"mysten_util_mem":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"mysten_util_mem/struct.MemoryStatsError.html\" title=\"struct mysten_util_mem::MemoryStatsError\">MemoryStatsError</a>"]],
"narwhal_config":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_config/enum.ConfigError.html\" title=\"enum narwhal_config::ConfigError\">ConfigError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_config/enum.CommitteeUpdateError.html\" title=\"enum narwhal_config::CommitteeUpdateError\">CommitteeUpdateError</a>"]],
"narwhal_consensus":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_consensus/dag/enum.ValidatorDagError.html\" title=\"enum narwhal_consensus::dag::ValidatorDagError\">ValidatorDagError</a>"]],
"narwhal_dag":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_dag/node_dag/enum.NodeDagError.html\" title=\"enum narwhal_dag::node_dag::NodeDagError\">NodeDagError</a>"]],
"narwhal_executor":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_executor/enum.SubscriberError.html\" title=\"enum narwhal_executor::SubscriberError\">SubscriberError</a>"]],
"narwhal_primary":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_primary/block_synchronizer/handler/enum.Error.html\" title=\"enum narwhal_primary::block_synchronizer::handler::Error\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_primary/block_synchronizer/enum.SyncError.html\" title=\"enum narwhal_primary::block_synchronizer::SyncError\">SyncError</a>"]],
"narwhal_types":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_types/error/enum.DagError.html\" title=\"enum narwhal_types::error::DagError\">DagError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_types/enum.HeaderBuilderError.html\" title=\"enum narwhal_types::HeaderBuilderError\">HeaderBuilderError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"narwhal_types/enum.DigestError.html\" title=\"enum narwhal_types::DigestError\">DigestError</a>"]],
"sui_faucet":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sui_faucet/enum.FaucetError.html\" title=\"enum sui_faucet::FaucetError\">FaucetError</a>"]],
"sui_indexer":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sui_indexer/errors/enum.IndexerError.html\" title=\"enum sui_indexer::errors::IndexerError\">IndexerError</a>"]],
"sui_json":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"sui_json/struct.SuiJsonValueError.html\" title=\"struct sui_json::SuiJsonValueError\">SuiJsonValueError</a>"]],
"sui_json_rpc":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sui_json_rpc/error/enum.Error.html\" title=\"enum sui_json_rpc::error::Error\">Error</a>"]],
"sui_sdk":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sui_sdk/error/enum.RpcError.html\" title=\"enum sui_sdk::error::RpcError\">RpcError</a>"]],
"sui_source_validation":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sui_source_validation/enum.SourceVerificationError.html\" title=\"enum sui_source_validation::SourceVerificationError\">SourceVerificationError</a>"]],
"sui_storage":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sui_storage/mutex_table/enum.TryAcquireLockError.html\" title=\"enum sui_storage::mutex_table::TryAcquireLockError\">TryAcquireLockError</a>"]],
"sui_types":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sui_types/error/enum.SuiError.html\" title=\"enum sui_types::error::SuiError\">SuiError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"sui_types/error/struct.ExecutionError.html\" title=\"struct sui_types::error::ExecutionError\">ExecutionError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sui_types/base_types/enum.ObjectIDParseError.html\" title=\"enum sui_types::base_types::ObjectIDParseError\">ObjectIDParseError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"sui_types/messages/enum.ExecutionFailureStatus.html\" title=\"enum sui_types::messages::ExecutionFailureStatus\">ExecutionFailureStatus</a>"]],
"typed_store":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"typed_store/rocks/enum.TypedStoreError.html\" title=\"enum typed_store::rocks::TypedStoreError\">TypedStoreError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()